# LEGAL NOTICE
# This computer software was prepared by Battelle Memorial Institute,
# hereinafter the Contractor, under Contract No. DE-AC05-76RL0 1830
# with the Department of Energy (DOE). NEITHER THE GOVERNMENT NOR THE
# CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY
# LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this
# sentence must appear on any copies of this computer software.
# 
# EXPORT CONTROL
# User agrees that the Software will not be shipped, transferred or
# exported into any country or used in any manner prohibited by the
# United States Export Administration Act or any other applicable
# export laws, restrictions or regulations (collectively the "Export Laws").
# Export of the Software may require some form of license or other
# authority from the U.S. Government, and failure to obtain such
# export control license may result in criminal liability under
# U.S. laws. In addition, if the Software is identified as export 
# controlled items under the Export Laws, User represents and warrants 
# that User is not a citizen, or otherwise located within, an embargoed 
# nation (including without limitation Iran, Syria, Sudan, Cuba, and 
# North Korea) and that User is not otherwise prohibited under the 
# Export Laws from receiving the Software.
# 
# Copyright 2011 Battelle Memorial Institute.  All Rights Reserved.
# Distributed as open-source under the terms of the Educational Community 
# License version 2.0 (ECL 2.0). http://www.opensource.org/licenses/ecl2.php
# 
# For further details, see: http://www.globalchange.umd.edu/models/gcam/


# diagnostics_USA.R
#
# An automated graphing system to process GCAM output data (as generated by the
# ModelInterface) and generate both standard and user-defined graphs.
#
# This file is the main entry point to the backend system.
#
# Ben Bond-Lamberty, November 2012
# Matthew Binsted, August 2017


# Load all support functions into memory
source( "scripts/diag_header_USA.R" )	# configuration and helper functions
source( "scripts/diag_parser_USA.R" )	# parser to read "ModelInterface" style CSVs
source( "scripts/diag_grapher_USA.R" )  # functions to generate figures
source( "scripts/color_schemes_USA.R" ) # some predefined color schemes
source( "scripts/diag_util_functions_USA.R" ) # library of useful utility functions

logstart( "diagnostics.R", savelog=F )

# ============================================================================
# REQUIRED: model interface output file(s) to read
# NOTE: All scenarios to be plotted should be contained within a single csv
# produced by a batch query.  User must always define a BASE_SCENARIO_NAME, 
# even if csv only contains one scenario.
FILES <- c( "gcam_data/EPSA_MLS_diagnostic_test.csv" )
BASE_SCENARIO_NAME <- "GCAM_USA_Ref_MLS"

# Region Mappings
grid_mapping <- read.csv("mappings/grid_region_mapping.csv", comment.char = "#")
EIA_state_mapping <- read.csv("mappings/EIA_state_mapping.csv", comment.char = "#")
state_census_region <- read.csv("mappings/state_census_region.csv", skip = 1)

# Technology Mappings
elec_mapping <- read.csv("mappings/elec_tech_coalret_mapping.csv", comment.char = "#")
EIA_tech_mapping <- read.csv("mappings/EIA_tech_mapping.csv", comment.char = "#")
bldg_mapping <- read.csv("mappings/bldg_energy_mapping.csv", skip = 1)
indust_mapping <- read.csv("mappings/indust_energy_mapping.csv", skip = 1)
trans_mapping <- read.csv("mappings/transp_energy_mapping.csv", skip = 1)
liquids_mapping <- read.csv("mappings/refined_liquids_mapping.csv", skip = 1)

# EIA historical data to read
gen_elec_power <- read_csv("gcam_data/EIA/Net_generation_for_electric_power.csv", skip = 4)
gen_comm_nonCHP <- read_csv("gcam_data/EIA/Net_generation_for_commercial_non-cogen.csv", skip = 4)
gen_resid <- read_csv("gcam_data/EIA/Net_generation_for_residential.csv", skip = 4)

# ============================================================================
# OPTIONAL: set output directory.
OUTPUT_DIR <- "figures"

# ============================================================================
# REQUIRED: parse data, building list of tables and output directory name
printlog( "-------- Reading data --------" )
tables <- list()
for( fn in FILES ) {
	tables[[ fn ]] <- parse_mi_output( fn )
}

# ============================================================================
# Some constants and conversion factors

FIGURE_DIMS <- list(dpi=300/2, width=3300/300, height=1860/300)

# Conversions 
conv_1975_2005_USD <- 2.956
conv_1990_2005_USD <- 1.336
conv_2000_2005_USD <- 1.086
conv_mil_bil <- 1e-3
Conversion_GJ_barrel <- 0.163
Conversion_GJ_mmBTU <- 0.948
Conversion_GJ_kWh <- 277.8
# NOTE:  GJ_kWh is equivalent to EJ_TWh
Conversion_kMWh_TWh <- 1e-3


# ============================================================================
# Generate graphs

printlog( "-------- Plotting --------" )

# ============================================================================
# Electricity Generation

# Prepare GCAM electricity generation data
printlog( "Electricity Generation by Technology" )
elec_gen_state <- extract_data("Multiple load segments Electricity generation by technology (inc solar roofs)")
elec_gen_state %>% select(-sector, -subsector) %>%
  filter(Year >= 2010, Year <= 2050) %>%
  mutate(value = value * Conversion_GJ_kWh) %>% 
  mutate(Units = "TWh") %>%
  left_join(elec_mapping, by = c("technology")) %>%
  filter(aggregate_tech != "") %>%
  left_join(grid_mapping, by = c("region")) %>% 
  mutate(grid_region = as.character(grid_region)) %>%
  mutate(country = "USA") %>%
  mutate(country = as.character(country)) -> elec_gen_state

# Rename scenarios if desired
# Format is mutate(scenario = ifelse((scenario == "current_scenario_name", "new_scenario_name", scenario))
# Repeat as necessary for each scenario in batch file 
elec_gen_state %>%  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS", "Ref", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_GDP_pop_upd2", "GDP_update", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_coalret_slow.3", "Coal_retire", scenario)) -> elec_gen_state

# Plot state totals, sorted by grid region
elec_gen_state[TITLE_FIELD_NAME] <- "State electricity generation by technology"
p <- ggplot(elec_gen_state) + geom_col(aes(x=Year, y=value, fill=aggregate_tech)) +
  facet_grid(region ~ scenario) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("grid_region"))

# Plot grid region totals
elec_gen_state[TITLE_FIELD_NAME] <- "Grid electricity generation by technology"
p <- ggplot(elec_gen_state) + geom_col(aes(x=Year, y=value, fill=aggregate_tech)) +
  facet_grid(. ~ scenario) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("grid_region"))

# Plot USA totals
elec_gen_state[TITLE_FIELD_NAME] <- "USA electricity geneneration by technology"
p <- ggplot(elec_gen_state) + geom_col(aes(x=Year, y=value, fill=aggregate_tech)) +
  facet_grid(. ~ scenario) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("country"))

# ============================================================================
# Electricity generation - EIA comparison (totals)
# Prepare EIA data
# Combine datasets (), 
# NOTE: Because of a quirk with EIA's electricity data browser, data for 
# "all utility-scale solar" is printed twice.  Thus, we group by description 
# in gen_elec_power and gen_comm_nonCHP and filter row_number() == 1 to remove 
# the duplicate values.
gen_elec_power %>% group_by(description) %>%
  filter(row_number() == 1) %>%
  bind_rows(gen_comm_nonCHP %>% 
              group_by(description) %>%
              filter(row_number() == 1)) %>%
  bind_rows(gen_resid) %>%  
  select(-`source key`) %>%
  filter(units != "NA") %>%
  separate(description, c("state", "fuel"), sep = " : ", remove = TRUE) %>%
  filter(fuel != "NA") %>%
  gather(Year, value, -state, -fuel, -units) %>%
  mutate(Year = as.numeric(Year)) %>%
  filter(Year %in% c(2010, 2015)) %>%
  mutate(value = as.numeric(value)) %>%
  filter(value != "NA") %>%
  mutate(value = value * Conversion_kMWh_TWh) %>%
  mutate(units = "TWh") %>%
  rename(Units = units) %>%
  mutate(scenario = "EIA") %>%
  left_join(EIA_state_mapping, by = c("state")) %>%
  mutate(country = "USA") %>%
  left_join(EIA_tech_mapping, by = c("fuel")) %>%
  filter(aggregate_tech != "") %>%
  select(-state) -> EIA_elec_gen

# Filter GCAM data, merge with EIA data
elec_gen_state %>% filter(Year >= 2010, Year <= 2015) %>% 
  select(-date, -file) %>%
  bind_rows(EIA_elec_gen) %>%
  mutate(Year = as.character(Year)) -> elec_gen_recent

# Plot state totals, sorted by grid region
printlog( "Electricity Generation by Technology" )
elec_gen_recent[TITLE_FIELD_NAME] <- "State electricity generation by technology - EIA comparison"
p <- ggplot(elec_gen_recent) + geom_col(aes(x=scenario, y=value, fill=aggregate_tech)) +
  facet_grid(region ~ Year) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("grid_region"))

# Plot grid region totals
elec_gen_recent[TITLE_FIELD_NAME] <- "Grid electricity generation by technology - EIA comparison"
p <- ggplot(elec_gen_recent) + geom_col(aes(x=scenario, y=value, fill=aggregate_tech)) +
  facet_grid(. ~ Year) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("grid_region"))

# Plot USA totals
elec_gen_recent[TITLE_FIELD_NAME] <- "USA electricity generation by technology - EIA comparison"
p <- ggplot(elec_gen_recent) + geom_col(aes(x=scenario, y=value, fill=aggregate_tech)) +
  facet_grid(. ~ Year) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("country"))

# ============================================================================
# Electricity generation fuel blends (%) - EIA comparison
elec_gen_recent %>% group_by(scenario, region, Year, aggregate_tech) %>%
  summarise(value = sum(value)) %>%
  filter(aggregate_tech != "") %>%
  group_by(scenario, region, Year) %>%
  mutate(total = sum(value)) %>% 
  mutate(pct = (value / total) * 100) %>% 
  mutate(Units = "%") %>%
  left_join(grid_mapping, by = c("region")) -> elec_pct_state
elec_gen_recent %>% group_by(scenario, grid_region, Year, aggregate_tech) %>%
  summarise(value = sum(value)) %>%
  filter(aggregate_tech != "") %>%
  group_by(scenario, grid_region, Year) %>%
  mutate(total = sum(value)) %>% 
  mutate(pct = (value / total) * 100) %>% 
  mutate(Units = "%") -> elec_pct_grid
elec_gen_recent %>% group_by(scenario, country, Year, aggregate_tech) %>%
  summarise(value = sum(value)) %>%
  filter(aggregate_tech != "") %>%
  group_by(scenario, Year) %>%
  mutate(total = sum(value)) %>% 
  mutate(pct = (value / total) * 100) %>% 
  mutate(Units = "%") -> elec_pct_USA

# Plot state fuel blends (%), sorted by grid region
printlog( "Electricity Generation by Technology" )
elec_pct_state[TITLE_FIELD_NAME] <- "State electricity generation by technology - EIA comparison"
p <- ggplot(elec_pct_state) + geom_col(aes(x=scenario, y=pct, fill=aggregate_tech)) +
  facet_grid(region ~ Year) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("grid_region"))

# Plot grid region fuel blends (%)
elec_pct_grid[TITLE_FIELD_NAME] <- "Grid electricity generation by technology - EIA comparison"
p <- ggplot(elec_pct_grid) + geom_col(aes(x=scenario, y=pct, fill=aggregate_tech)) +
  facet_grid(. ~ Year) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("grid_region"))

# Plot USA fuel blend (%)
elec_pct_USA[TITLE_FIELD_NAME] <- "USA electricity generation by technology - EIA comparison"
p <- ggplot(elec_pct_USA) + geom_col(aes(x=scenario, y=pct, fill=aggregate_tech)) +
  facet_grid(. ~ Year) + scale_fill_manual(values=elec_tech_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("country"))

# ============================================================================
# Building Energy Consumption

# Prepare data, including USA "global sum"
printlog( "Final Energy Consumption: Buildings" )
building_energy <- extract_data("Building final energy by technology and fuel")
building_energy %>% filter(Year >= 2010, Year <= 2050) %>%
  left_join(bldg_mapping, by = c("input")) %>% 
  add_global_sum %>%
  mutate(region = ifelse(region == "Global", "USA", region)) %>%
  compute_energy_reduction("Fuel") %>%
  filter(value > 0) %>%
  mutate(value = ifelse(Fuel == "energy reduction", (value * -1), value)) -> building_energy

# Rename scenarios if desired
# Format is mutate(scenario = ifelse((scenario == "current_scenario_name", "new_scenario_name", scenario))
# Repeat as necessary for each scenario in batch file 
building_energy %>%  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS", "Ref", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_GDP_pop_upd2", "GDP_update", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_coalret_slow.3", "Coal_retire", scenario)) -> building_energy

# Plot results (state + USA)
building_energy[TITLE_FIELD_NAME] <- "Final Energy Consumption: Buildings"
p <- ggplot(building_energy) + geom_col(aes(x=Year, y=value, fill=Fuel)) +
  facet_grid(. ~ scenario) + scale_fill_manual(values=building_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("region"))

# ============================================================================
# Industry Energy Consumption

printlog( "Final Energy Consumption: Industry" )
indust_energy <- extract_data("Industry final energy by technology and fuel")
indust_energy %>% filter(Year >= 2010, Year <= 2050) %>%
  left_join(indust_mapping, by = c("input")) %>% 
  add_global_sum %>%
  mutate(region = ifelse(region == "Global", "USA", region)) %>%
  compute_energy_reduction("Fuel") %>%
  filter(value >= 0) %>%
  mutate(value = ifelse(Fuel == "energy reduction", (value * -1), value)) -> indust_energy

# Rename scenarios if desired
# Format is mutate(scenario = ifelse((scenario == "current_scenario_name", "new_scenario_name", scenario))
# Repeat as necessary for each scenario in batch file 
indust_energy %>%  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS", "Ref", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_GDP_pop_upd2", "GDP_update", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_coalret_slow.3", "Coal_retire", scenario)) -> indust_energy

# Plot results (state + USA)
indust_energy[TITLE_FIELD_NAME] <- "Final Energy Consumption: Industry"
p <- ggplot(indust_energy) + geom_bar(aes(x=Year, y=value, fill=Fuel), stat="identity") +
  facet_grid(. ~ scenario) + scale_fill_manual(values=indust_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("region"))

#do_graph_YearSubset(p, page_variables=c("region", "scenario"))
#do_graph(create_diff_plot(p), page_variables=c("region", "scenario"))

# ============================================================================
# Transportation Energy Consumption

printlog( "Final Energy Consumption: Transportation" )
trans_energy <- extract_data("Transportation final energy by technology and fuel")
trans_energy %>% filter(Year >= 2010, Year <= 2050) %>%
  left_join(trans_mapping, by = c("input")) %>% 
  add_global_sum %>%
  mutate(region = ifelse(region == "Global", "USA", region)) %>%
  compute_energy_reduction("Fuel") %>%
  filter(value >= 0) %>%
  mutate(value = ifelse(Fuel == "energy reduction", (value * -1), value)) -> trans_energy

# Rename scenarios if desired
# Format is mutate(scenario = ifelse((scenario == "current_scenario_name", "new_scenario_name", scenario))
# Repeat as necessary for each scenario in batch file 
trans_energy %>%  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS", "Ref", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_GDP_pop_upd2", "GDP_update", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_coalret_slow.3", "Coal_retire", scenario)) -> trans_energy

# Plot results (state + USA)
trans_energy[TITLE_FIELD_NAME] <- "Final Energy Consumption: Transportation"
p <- ggplot(trans_energy) + geom_bar(aes(x=Year, y=value, fill=Fuel), stat="identity") +
  facet_grid(. ~ scenario) + scale_fill_manual(values=trn_fuel_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("region"))
# do_graph(split_neg_geom_bar(create_diff_plot(p)), page_variables=c("region"))

# ============================================================================
# Refined Liquids by Fuel

printlog( "Refined Liquids by Fuel" )
refined_liquids <- extract_data("Refined liquids production by technology")
refined_liquids %>% filter(Year >= 2010, Year <= 2050) %>%
  left_join(liquids_mapping, by = c("technology")) %>% 
  add_global_sum %>%
  mutate(region = ifelse(region == "Global", "USA", region)) %>%
  compute_energy_reduction("Fuel") %>%
  filter(value >= 0) %>%
  mutate(value = ifelse(Fuel == "energy reduction", (value * -1), value)) -> refined_liquids

# Rename scenarios if desired
# Format is mutate(scenario = ifelse((scenario == "current_scenario_name", "new_scenario_name", scenario))
# Repeat as necessary for each scenario in batch file 
refined_liquids %>%  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS", "Ref", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_GDP_pop_upd2", "GDP_update", scenario)) %>%
  mutate(scenario = ifelse(scenario == "GCAM_USA_Ref_MLS_coalret_slow.3", "Coal_retire", scenario)) -> refined_liquids

# Plot results (state + USA)
refined_liquids[TITLE_FIELD_NAME] <- "Refined Liquids by Fuel"
p <- ggplot(refined_liquids) + geom_bar(aes(x=Year, y=value, fill=Fuel), stat="identity") +
  facet_grid(. ~ scenario) + scale_fill_manual(values=liquids_fuel_colors)
p$save_args <- FIGURE_DIMS
do_graph(split_neg_geom_bar(p), page_variables=c("region"))
# do_graph(split_neg_geom_bar(create_diff_plot(p)), page_variables=c("region"))

# ============================================================================
generate_html_index()

# ============================================================================
logstop()
