# Copyright 2019 Battelle Memorial Institute; see the LICENSE file.

#' module_energy_LA155.EMF37_transportation_data
#'
#' Generates transportation energy and other data using UCD transportation database and IEA data.
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs,
#' a vector of output names, or (if \code{command} is "MAKE") all
#' the generated outputs: \code{L154.in_EJ_R_trn_m_sz_tech_F_Yh}, \code{L154.in_EJ_ctry_trn_m_sz_tech_F}, \code{L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y}, \code{L154.loadfactor_R_trn_m_sz_tech_F_Y}, \code{L154.cost_usdvkm_R_trn_m_sz_tech_F_Y}, \code{L154.speed_kmhr_R_trn_m_sz_tech_F_Y}, \code{L154.out_mpkm_R_trn_nonmotor_Yh}. The corresponding file in the
#' original data system was \code{LA154.transportation_UCD.R} (energy level1).
#' @details L154.in_EJ_R_trn_m_sz_tech_F_Yh and L154.in_EJ_ctry_trn_m_sz_tech_F generated by aggregating IEA data UCD
#' transportation technologies, then scaling to transportation enduse data. Other outputs generated by aggregating UCD data
#' to GCAM regions.
#' @importFrom assertthat assert_that
#' @importFrom dplyr arrange bind_rows distinct filter if_else group_by left_join mutate select summarise group_by select
#' @importFrom tidyr gather replace_na spread
#' @importFrom data.table as.data.table setorderv rbindlist
#' @importFrom rlang :=
#' @author RH May 2017
module_energy_LA155.EMF37_transportation_data <- function(command, ...) {

  if(command == driver.DECLARE_INPUTS) {
    return(c("UCD_trn_data",
             "L154.in_EJ_R_trn_m_sz_tech_F_Yh",
             "L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y",
             "L154.loadfactor_R_trn_m_sz_tech_F_Y",
             "L154.cost_usdvkm_R_trn_m_sz_tech_F_Y",
             "L154.speed_kmhr_R_trn_m_sz_tech_F_Y"))
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(c("EMF37_transport_data"))
  } else if(command == driver.MAKE) {

    ## silence package check.
    year <- value <- NULL

    all_data <- list(...)[[1]]

    # Load required inputs
    UCD_trn_data <- get_data(all_data, "UCD_trn_data")
    L154.in_EJ_R_trn_m_sz_tech_F_Yh <- get_data(all_data, "L154.in_EJ_R_trn_m_sz_tech_F_Yh")
    L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y <- get_data(all_data, "L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y")
    L154.loadfactor_R_trn_m_sz_tech_F_Y <- get_data(all_data, "L154.loadfactor_R_trn_m_sz_tech_F_Y")
    L154.cost_usdvkm_R_trn_m_sz_tech_F_Y <- get_data(all_data, "L154.cost_usdvkm_R_trn_m_sz_tech_F_Y")
    L154.speed_kmhr_R_trn_m_sz_tech_F_Y <- get_data(all_data, "L154.speed_kmhr_R_trn_m_sz_tech_F_Y")

    ### Compile and write out USA-specific transportation data for the 2015 base year, for the EMF37 project
    ### TODO - remove this at core model PR stage
    EMF37_data_years <- seq(2015, 2100, 5)
    EMF37_transport_data <- bind_rows(
      filter(L154.in_EJ_R_trn_m_sz_tech_F_Yh, GCAM_region_ID == 1 & year %in% EMF37_data_years) %>%
        mutate(variable = "energy",
               unit = "EJ/yr"),
      filter(L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y,
             GCAM_region_ID == 1 & year  %in% EMF37_data_years & sce == "CORE") %>%
        mutate(variable = "intensity",
               unit = "MJ/vkm"),
      filter(L154.loadfactor_R_trn_m_sz_tech_F_Y,
             GCAM_region_ID == 1 & year  %in% EMF37_data_years & sce == "CORE") %>%
        mutate(variable = "load factor",
               unit = if_else(UCD_sector == "Passenger", "persons per vehicle", "tonnes per vehicle")),
      filter(L154.cost_usdvkm_R_trn_m_sz_tech_F_Y,
             GCAM_region_ID == 1 & year  %in% EMF37_data_years & sce == "CORE") %>%
        mutate(variable = "levelized non-fuel cost",
               unit = "$/vkm (2019$)",
               value = value * gdp_deflator(2019, 2005)),
      filter(L154.speed_kmhr_R_trn_m_sz_tech_F_Y,
             GCAM_region_ID == 1 & year  %in% EMF37_data_years & sce == "CORE" & UCD_sector == "Passenger") %>%
        mutate(variable = "speed",
               unit = "km/hr")
    ) %>%
      mutate(region = "USA",
             value = round(value, 5)) %>%
      select(-fuel) %>%
      select(region, sector = UCD_sector, mode, size.class, technology = UCD_technology, fuel = UCD_fuel, year, variable, unit, value)

    # Estimate the capital (not levelized) costs of light duty vehicles
    EMF37_vehicle_output <- filter(UCD_trn_data, sce == "CORE" & UCD_region == "USA" & mode == "LDV_4W" & variable == "energy" & year == 2005) %>%
      mutate(join_variable = "intensity", join_unit = "MJ/vkm") %>%
      left_join(UCD_trn_data, by = c("UCD_region", "UCD_sector", "mode", "size.class",
                                     "UCD_technology", "UCD_fuel", join_variable = "variable",
                                     join_unit = "unit", "year", "sce", "rev.mode", "rev_size.class")) %>%
      group_by(UCD_region, UCD_sector, mode, size.class) %>%
      mutate(size.class.energy = max(value.x)) %>%
      ungroup() %>%
      mutate(weight = size.class.energy / value.y) %>%
      select(UCD_sector, mode, size.class, UCD_technology, UCD_fuel, weight)

    EMF37_vehicle_cost_data <- filter(UCD_trn_data, sce == "CORE" & UCD_region == "USA" & mode == "LDV_4W" & variable == "Capital costs (purchase)") %>%
      left_join_error_no_match(EMF37_vehicle_output,
                               by = c("UCD_sector", "mode", "size.class", "UCD_technology", "UCD_fuel")) %>%
      mutate(weighted_cost = value * weight) %>%
      group_by(UCD_sector, rev.mode, rev_size.class, UCD_fuel, UCD_technology, year) %>%
      summarise(weight = sum(weight),
                weighted_cost = sum(weighted_cost)) %>%
      ungroup() %>%
      mutate(value = round(weighted_cost / weight * gdp_deflator(2019, 2005), 0),
             region = "USA",
             variable = "Purchase price",
             unit = "$/vehicle (2019$)") %>%
      select(region, sector = UCD_sector, mode = rev.mode, size.class = rev_size.class,
             technology = UCD_technology, fuel = UCD_fuel, year, variable, unit, value)

    EMF37_transport_data <- bind_rows(EMF37_transport_data, EMF37_vehicle_cost_data) %>%
      filter(year >= 2015 & year <= 2050) %>%
      spread(key = year, value = value) %>%
      add_title("Transportation database for EMF37 inter-comparison exercise") %>%
      add_units("Indicated within table") %>%
      add_comments("All variables required for transportation models") %>%
      add_precursors("UCD_trn_data",
                     "L154.in_EJ_R_trn_m_sz_tech_F_Yh",
                     "L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y",
                     "L154.loadfactor_R_trn_m_sz_tech_F_Y",
                     "L154.cost_usdvkm_R_trn_m_sz_tech_F_Y",
                     "L154.speed_kmhr_R_trn_m_sz_tech_F_Y") ->
      EMF37_transport_data

    return_data(EMF37_transport_data)
  } else {
    stop("Unknown command")
  }
}
